name: Workflow

on:
  push:
    branches:
      - main
      - dev
      - stagin
      - feature-*
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  formatting-and-linting:
    name: Run Prettier and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run Prettier Check
        run: npx prettier --check .

      - name: Run Lint
        run: npm run lint

  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: [formatting-and-linting]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run Jest Tests with Coverage
        run: npm test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
